spring:
    application:
        name: order-service

    datasource:
        password: postgres
        url: jdbc:postgresql://localhost:5432/travels
        username: postgres

    rabbitmq:
        addresses: localhost:5672
        username: guest
        password: guest    

server:
    port: 8030

api:
    key: '"FX001-FREE"'
    version: '2020-12-29'
                
release:
    version: 5.0.0


eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/


logging.level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web.reactive.function.client: TRACE


resilience4j.circuitbreaker:
  instances:
    travelClientCircuitBreaker:
      registerHealthIndicator: true
      slidingWindowSize: 60
      slidingWindowType: TIME_BASED
      permittedNumberOfCallsInHalfOpenState: 3
      minimumNumberOfCalls: 10
      waitDurationInOpenState: 5s
      slowCallRateThreshold: 100
      slowCallDurationThreshold: 2000
      failureRateThreshold: 50
   
management:
  endpoint:
    health:
      show-details: always         #To show all details in /health endpoint.

  endpoints:
      web:
         exposure:
            include: "*"

management.health.circuitbreakers.enabled: true #To show Circuit Breaker status

