spring:
    application:
        name: order-service

    datasource:
        password: postgres
        url: jdbc:postgresql://localhost:5432/travels
        username: postgres

    rabbitmq:
        addresses: localhost:5672
        username: guest
        password: guest    

server:
    port: 8040

api:
    key: '"FX001-FREE"'
    version: '2020-12-29'
                
release:
    version: 5.0.0


eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/


logging.level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web.reactive.function.client: TRACE
