spring:
    application:
        name: fallback-service

    rabbitmq:
        addresses: localhost:5672
        username: guest
        password: guest    

server:
    port: 8015

                
release:
    version: 5.0.0


eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/


logging.level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web.reactive.function.client: TRACE

   
management:
  endpoint:
    health:
      show-details: always         #To show all details in /health endpoint.

  endpoints:
      web:
         exposure:
            include: "*"


