spring:
    application:
        name: gateway-service

    cloud:
      gateway:
          discovery:
            locator:
              enabled: true
              lowerCaseServiceId: true
          routes:        
            - id: customer-service
              uri: lb://CUSTOMER-SERVICE
              predicates:
                - Path=/api-customer/v1/customer/**
             

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      

    
server:
    port: 8010



logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

logging.level.io.github.resilience4j: DEBUG

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 10
      minimumNumberOfCalls: 5
      permittedNumberOfCallsInHalfOpenState: 3
      automaticTransitionFromOpenToHalfOpenEnabled: true
      waitDurationInOpenState: 2s
      failureRateThreshold: 5
      eventConsumerBufferSize: 10
      slowCallDurationThreshold: 200ms
      slowCallRateThreshold: 30
      recordExceptions:
        - org.springframework.web.client.HttpServerErrorException
        - java.io.IOException
      ignoreExceptions:
        - java.lang.IllegalStateException
    shared:
      slidingWindowSize: 100
      permittedNumberOfCallsInHalfOpenState: 30
      waitDurationInOpenState: 1s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10
      ignoreExceptions:
        - java.lang.IllegalStateException
  instances:
    customer-service:
      baseConfig: default
    order-service:
      slidingWindowSize: 10
      minimumNumberOfCalls: 10
      permittedNumberOfCallsInHalfOpenState: 3
      waitDurationInOpenState: 1s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10
      recordFailurePredicate: io.github.romeh.services.gateway.HttpInternalServicePredicate


management:
   endpoint:
      gateway:
         enabled: true
   endpoints:
      web:
         exposure:
            include: "*"


