spring:
    application:
        name: gateway-service

    cloud:
      gateway:
          discovery:
            locator:
              enabled: true
              lowerCaseServiceId: true
          routes:        
            - id: customer-service
              uri: lb://CUSTOMER-SERVICE
              predicates:
                  - Path=/api-customer/v1/customer/**
            - id: travel
              uri: lb://travel-service
              predicates:
                  - Path=/api-travel/v1/travel/**
            - id: order
              uri: lb://order-service
              predicates:
                  - Path=/api-order/v1/order/**
              filters:
                - StripPrefix=1              
        
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      

    
server:
    port: 8010



logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
  level:
      org.springframework: DEBUG

management:
   endpoint:
      gateway:
         enabled: true
   endpoints:
      web:
         exposure:
            include: gateway        


