spring:
    application:
        name: gateway-service



eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      

    
server:
    port: 8010



logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
  level:
      org.springframework: DEBUG

management:
   endpoint:
      gateway:
         enabled: true
   endpoints:
      web:
         exposure:
            include: gateway        


