spring:
    application:
        name: gateway-service
    
    cloud:
      gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: customer
        uri: lb://customer
        predicates:
        - Path=/api-customer/v1/customer/**
      - id: travel
        uri: lb://travel
        predicates:
        - Path=/api-travel/v1/travel/**
      - id: order
        uri: lb://order
        predicates:
        - Path=/api-order/v1/order/**

server:
    port: 8010


eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/

logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

management:
   endpoint:
      gateway:
         enabled: true
   endpoints:
      web:
         exposure:
            include: gateway        
