spring:
    application:
        name: gateway-service

    cloud:
      gateway:
          discovery:
            locator:
              enabled: true
              lowerCaseServiceId: true
          routes:        
            - id: customer-service
              uri: lb://CUSTOMER-SERVICE
              predicates:
                - Path=/api-customer/v1/customer/**
              filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 60
                redis-rate-limiter.requestedTokens: 15
                       
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      

    
server:
    port: 8010



logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"


management:
   endpoint:
      gateway:
         enabled: true
   endpoints:
      web:
         exposure:
            include: gateway        


