spring:
    application:
        name: gateway-service

server:
    port: 8010
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/

logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
              
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: customer
        uri: lb://customer
        predicates:
        - Path=/customer/**
        filters:
        - RewritePath=/customer/(?<path>.*), /api-customer/v1/customer/$\{path}
      - id: travel
        uri: lb://travel
        predicates:
        - Path=/travel/**
        filters:
        - RewritePath=/travel/(?<path>.*), /api-travel/v1/travel/$\{path}
      - id: order
        uri: lb://order
        predicates:
        - Path=/order/**
        filters:
        - RewritePath=/order/(?<path>.*), /api-order/v1/order/$\{path}   

management:
   endpoint:
      gateway:
         enabled: true
   endpoints:
      web:
         exposure:
            include: gateway        
            
ribbon:
  eureka:
    enabled: true            